# Lineáris egyenletrendszerek

## Általánosan a lineáris egyenletredszerekről

A lineáris egyenletrendszer egy többismeretlenes egyenletrendszer melyben az ismeretlenek az első hatványon vannak.

Egy $n$ egyenlet és $m$ változó esetén az egyenletrendszer általános alakja a következő:           

$$
x_{1,1} + x_{1,2} + \dots + x_{1,m} = b_{1}\\
x_{2,1} + x_{2,2} + \dots + x_{2,m} = b_{2}\\
\vdots\\
x_{i,1} + x_{i,2} + \dots + x_{i,m} = b_{i}\\
\vdots\\
x_{n,1} + x_{n,2} + \dots + x_{n,m} = b_{n}\\
$$

Aztmondjuk hogy az egyenlet rendszer alulhatárolt, hogyha $n<m$ és túlhatárolt, hogyha $n>m$.
Négyzetesnek nevezzük ha $m=n$.
Az egyenletrendszer geometriai tartalmát az alábbi módon írhatjuk le:

Az $R^n$ euklideszi tér $d\in R^n$ normálvektorú és $x_0 \in R^n$ ponton átmenő hipersíkját az

$$ (x - x_0)^Td=0$$ 

egyenletet kielégítő $x \in R^n$ pontok határozzák meg.

Az $Ax=b$ egyenletrendszert felírhatjuk ilyen formában is:  

$$ 
a_{1}^Tx= b_1\\
a_{2}^Tx= b_2\\
\vdots\\
a_{n}^Tx= b_n\\
$$

ahol $a_{i}^T={a_{i1}, \dots a_{im}}$.

Innen láthatjuk, hogy az egynletrendszer megoldása az $m$ hipőersík közös része, ennek megfelelően 3 megoldás lehetséges:
1. lehetőség: nincs megolás
2. lehetőség: pontosan egy megoldása van
3. lehetőség: végtelen sok megoldás van

#### _Egynetrendszer konzisztenciája:_

_Ha az $Ax=b$ egyenletrendszernek legalább egy megoldása létezik konzisztensnek nevezzük. Ha nem létezik egyetlen megoldása sem, akkor az egyenletrendszer inkonzisztens._

## Lineáris egyenletrendszerek megoldása Pythonban, NumPy csomag segítségével

Egy egyenletrendszert megoldani pythonban nem nehéz. A `NumPy` tartalmazza a `solve` metódust mellyel könnyedén megoldható egy-egy lineáris egyenletrendszer. A `solve` a `NumPy` linalg csomagjában található, paramáterként várja az $A$ együtthatómátrixot és a $b$ megoldásvektort. Nézzük is meg:

Vegyünk először egy egyszerű egyenletrendszert, mint ez:
$$
    2x_1 + 9x_2 + 8x_3 + 7x_4= 7\\
    3x_1 - 2x_2 + 6x_3 + 4x_4= 4\\
    5x_1 + 8x_2 + 4x_3 + 7x_4= 2\\
    6x_1 + 9x_2 + 10x_3 + 2x_4= 6
$$

ezután importáljuk a numpy csomagot

In [1]:
import numpy as np
import time #a futási idő méréséhez kell

Miután ezzel megvagyunk hozzuk létre az együttható métrixunkat és a megoldás vektorunkat:

In [2]:
a=np.array([[2,9,8,7], [3,-2,6,4],[5,8,4,7],[6,9,10,2]])
b=np.array([7,4,2,6])

Majd használjuk a `solve` metódust

In [3]:
start = time.time()
import numpy as np
x_solve=np.linalg.solve(a,b)
print(x_solve)
print("%.10f seconds"%(time.time()-start))
time_solve=time.time()-start

[-0.51762115  0.03597651  0.85279001  0.12701909]
0.0010077953 seconds


A solve az Intel Math Kernel Library-ben megtalálható LAPACK gesv rutint használja.

A futás időt is kiírattam itt, hogy később össze lehessen vetni a beépített és az általam implementált algoritmust.
Az `allclose` és`dot` metódusok segítségével pedig le is ellenőrízhetjük az eredményt.

In [4]:
np.allclose(np.dot(a, x_solve), b)

True

Ilyen egyszerű az egész, de ha nem szeretnénk az előre megírt metódust alkalmazni akkor definiálhatunk saját magunk is nekünk tetsző megoldó metódust is. Például implementálhatjuk a Gauss módszert is. Ám mielőtt ezt megnéznénk vessünk egy pillantást a ciklusokra pythonban csak, hogy érthető legyen a kód.

#### Rang 

Egy lineáris egyenletrendszer csak akkor megoldható ha az A matrixunk rangja megyegyezik a [A,b] mátrix rangjával ilyenkor az egyenletrendszerünknek pontosan egy megoldása van. Ezt pythonban a következő képpen tudjuk ellenőrizni: 

In [5]:
print("A mátrix rangja:")
print(np.linalg.matrix_rank(a))
c=np.column_stack((a,b.transpose()))
print("[A,b] mátrix rangja:")
print(np.linalg.matrix_rank(c))

A mátrix rangja:
4
[A,b] mátrix rangja:
4


Amint látjuk a két rang megegyezik ezáltal megoldható az itt látható egyenlet rendszer.

#### Ciklusok pythonban:

Pythonban is megtalálható a `for` és a `while` ciklus. A  `for` végig iterál egy iterálható objektumon ami pythonban lehet egy tömb, string vagy az általunk kreált iterálható struktúra. 

In [6]:
s="string"
tomb=[1,3,5]
collection=["string", 8, 'a']

for i in s:
    print(i)
    
print("\n") 

for i in tomb:
    print(i)
    
print("\n")

for i in collection:
    print(i)


s
t
r
i
n
g


1
3
5


string
8
a


Ha klasszikus értelemben szeretnénk használni (tehát egy ciklus változót léptetni egy kezdő értéktől egy végértékig) használnunk kell a `range` metódust mely generál egy tömböt a megadott paraméterek alapján. Három paramétere van, az első a kezdő érték, a második a végérték és a harmadik a lépésköz. A `range` esetében figyelni kell, mert a végéertékig generálja a számokat ezért a végérték nem szerepel az általa vissza adott tömbben.

In [7]:
x=range(1,4)

for i in x: 
    print(i)

print("\n")

for i in range(1,50,2):
    print(i)


1
2
3


1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49


A `while` működése nem tér el a többi általános célú programozási nyelvben megszokottól. Amíg a megadott feltételünk igaz addig maradunk a ciklusban.  

In [8]:
x=0
while x<10:
    x=x+1
    print(x)

1
2
3
4
5
6
7
8
9
10


 Nézzük még meg az `if` elágazást is mely megvizsgál egy logikai kifejezést és annak értéke szerint ágaztatja el a programot.

In [9]:
if True:
    print("igaz")
    
if False:
    print("igaz")
else:
    print("hamis")
    
if(2+2==4):
    print("two plus two is four")

igaz
hamis
two plus two is four


És akkor lássuk a Gauss módszer implementációját:

#### Gauss módszer pythonban:

In [22]:
# imports
import numpy as np
import time


# definition of Gauss elimintion function
def gauss(a, b, dimension):
    
    #variables
    l=np.zeros([dimension,dimension])
    x=np.zeros([dimension])
    
#Gauss elimination phase
#Making the upper triangle matrix

    for k in range(0, dimension-1):
        for i in range(k+1, dimension):
            l[i,k] = a[i,k] / a[k,k]
            b[i] = b[i] - (l[i,k] * b[k])
            for j in range(k,dimension):
                a[i,j] = a[i,j] - (l[i,k] * a[k,j])
    
    print("Az első fázis után így néz ki az A matrixunk:")
    print(a)      
#Gauss replacement phase 
#Calculate the x values

    x[dimension-1]= b[dimension-1]/a[dimension-1,dimension-1]
    
   ## for i in range(dimension):
     #   x[i]=b[i]/a[i,i]
      #  print (x[i])
        
    for i in range(dimension-1, -1, -1):
        s=0
        for j in range(i+1,dimension):
            s = s + a[i,j] * x[j]
            x[i] = (b[i] - s)/a[i,i]
             
            
    return(x)


start = time.time()
# initialization
a=np.array([[2,9,8,7], [3,-2,6,4],[5,8,4,7],[6,9,10,2]])
b=np.array([7,4,2,6])
dimension=4
x_g=gauss(a,b,dimension)
print(x_g)
time_gauss=time.time()-start
print(time_gauss)
      

Az első fázis után így néz ki az A matrixunk:
[[  2   9   8   7]
 [  0 -15  -6  -6]
 [  0   0 -10  -4]
 [  0   0   0  -8]]
[-0.3825  0.01    0.85    0.125 ]
0.0010013580322265625


Láthatjuk futás időben elég közel van a numpyban lévő megoldáshoz. De nem kapunk olyan pontos eredményt.

#### Főelem kiválasztás

A fenti algoritmus csak olyan mátrixokat képes megoldani amikben egyik együttható sem nulla. Hogy képes legyen rá ki kell egészíteni főelem kiválasztással. A főelem kiválasztás azt jelenti, hogy a sorokat úgy cseréljük fel, hogy az aktuális pivot elemünk ne legyen nulla. A főelemkiválasztás lehet részleges vagy teljes. Részleges főelem kiválasztásnál a $k$-adik lépésben megkeressük a $k$-adik oszlop elemei közül a maximális abszolút értékű $a_{ik}$ együtthatót és ez az $j$-edik sorban van akkor megcseréljük a $j$-edik és a $k$-adik sort. Ezzel fogunk majd találkozni a gauss-Jordan módszer implementációjánál. A teljes főelem kiválasztás során pedig a $k$-adik lépésben megkeressük a mátrixban szereplő értékek közül a maximális abszolút értékűt és ha ez a $a_{ij}$ akkor a $k$-adik sort felcseréljük az $i$-edikkel és a $k$-adik oszlopot is felcseréljük a $j$-edikkel.  

#### Gauss-Jordan módszer pythonban

Egy másik lehetséges módszer az egyenletrendszerek megoldására a Gauss-Jordan módszerezt leimplementálhatjuk mi magunk is, de én most egy másik csomagot a SymPy-t fogom segítségül hívni.
Első lépésnek vegyük az $A$ mátrixunkat és a $b$ vektorunkat, majd használjuk az A mátrixra definiált `gauss_jordan_solve` mmetódust melynek paraméterként a $b$ vektort adjuk meg. A metódus két visszatérési értéke a megoldás és a mátrix.

In [11]:
from sympy import Matrix

start=time.time()
A = Matrix([[2,9,8,7], [3,-2,6,4],[5,8,4,7],[6,9,10,2]])
b = Matrix([7,4,2,6])
sol, params = A.gauss_jordan_solve(b)

n,m =sol.shape
x_gj= np.zeros(n)
for i in range(0,n):
    x_gj[i]= sol[i]

time_gauss_jordan=time.time()-start
print(x_gj)
print(time_gauss_jordan)

[-0.51762115  0.03597651  0.85279001  0.12701909]
0.003010272979736328


Fontos, hogy a Matrixot nem kompatibilis az np.arrayel, így az értékeket nekünk kell áthelyezni.

Van egy 4. módszer is a lineáris egyenlet rendszer megoldására a `scipy` csomagban, ami az lu faktorizáción alapul. A metódus neve pedig `lu_solve` és az alábbi módon lehet használni:

In [12]:
from scipy.linalg import lu_factor, lu_solve

start=time.time()
A = np.array([[2,9,8,7], [3,-2,6,4],[5,8,4,7],[6,9,10,2]])
b = np.array([7,4,2,6])
lu, piv = lu_factor(A)
x_lu = lu_solve((lu, piv), b)

time_lu=time.time()-start
print(x_lu)
print(time_lu)

[-0.51762115  0.03597651  0.85279001  0.12701909]
0.0010383129119873047


Most lássunk egy összesítő táblázatot a 3 módszerről: 

In [30]:
import pandas as pd




df = pd.DataFrame(np.array([ [x_solve[0], x_solve[1], x_solve[2],x_solve[3], time_solve], [x_g[0], x_g[1], x_g[2],x_g[3], time_gauss], [x_gj[0], x_gj[1], x_gj[2],x_gj[3], time_gauss_jordan],[x_lu[0], x_lu[1], x_lu[2],x_lu[3], time_lu] ]),
                   columns=['x1', 'x2', 'x3','x4' ,'time'], index=['solve', 'gauss', 'gauss_jordan' , 'Lu'])

df

x1        x2       x3        x4      time
solve        -0.517621  0.035977  0.85279  0.127019  0.001008
gauss        -0.382500  0.010000  0.85000  0.125000  0.001001
gauss_jordan -0.517621  0.035977  0.85279  0.127019  0.003010
Lu           -0.517621  0.035977  0.85279  0.127019  0.001038