# Vektor és mátrix műveletek
## Vektor műveletek:

Pythonban a *NumPy* csomag használatával könnyedén definiálhatunk vektorokat és mátrixokat.
Ahhoz, hogy használhassuk előtte telepíteni kell majd be kell a pip csomagkezelővel, majd az alábbi módon lehet importálni:  

In [3]:
import numpy as np

Ez a szintaktikája pythonban egy csomag inportálásának az `as` operátor után aliast adhatunk a csomagnak, így megkönyítve a használatát. Alias megadása nem kötelező. 

Ebben. esetben `np`-vel tudunk hivatkozni a *NumPy* csomagra.
A csomagból az `array` metódus segítségével hozhatunk létre vektorokat.

In [4]:
v1 = np.array([1, 2, 3])
v2 = np.array([3, 2, 1])
v3 = np.array([5, 3, 1, 6])

Üres vektort a következőképpen készíthetünk: az `empty` metódusban meg kell adni szögletes zárójelek között egy dimenziót (például: `[1, 3]` ez azt jelenti 1 sort és 3 oszlopot szeretnénk), és esetlegesen megadhatunk neki egy adattípust, hogy milyen adatokkal szeretnénk feltölteni.

Itt főleg valmilyen numerikus adattípusra kell gondolni, hisz ezekkel tudjuk elvégezni a vektor és mátrix műveleteket. Haszálhatjuk a python beépített típusait mint az `int` vagy a `float`, de használhatjuk a *NumPy*-ban definiált kiegészített változatokat amivel megadhatjuk azt például, hogy hány bájton tároljuk az adott számot. Esetlegesen megadhatunk stringet és bool típust is ha szükség van rá.

In [ ]:
int

In [ ]:
float

In [ ]:
bool

In [ ]:
np.int8

In [ ]:
np.uint

In [ ]:
np.float32

In [5]:
v4 = np.empty([1, 3])
print(v4)

[[0. 0. 0.]]


Ahogy láthatjuk, nem 0-ákkal tölti fel a vektort hanem valamilyen memória szeméttel. Ennek az oka nagyon egyszerű: így gyorsabb, mint ha nullázná az elemeket, de ha 0-ákkal szeretnénk feltölteni használhatjuk a `zeros` metódust mely hasonló képpen működik mint az `empty`:

In [6]:
v4 = np.zeros([1, 3])
print(v4)


[[0. 0. 0.]]


1-esekkel is feltölthetjük ehez a `ones`metódust használhatjuk: 

In [7]:
v4 = np.ones([1, 3])
print(v4)

[[1. 1. 1.]]


Létrehozhatunk egy bizonyos értékkel vagy pszeudóvéletlen (random) számokkal feltöltött vektorokat is :

In [8]:
v5 = np.random.rand(1, 3)
v6 = np.full([1, 3], "aaa")
print(v5)
print(v6)

[[0.22541693 0.47521003 0.90312494]]
[['aaa' 'aaa' 'aaa']]


A fent létrehozott `v1`, `v2`, `v3` vektorainkal már egyszerűen elvégezhetőek a vektor műveletek, mint például az összeadás:

In [ ]:
print(v1 + v2)

vagy a kivonás:

In [ ]:
print(v1 - v2)

vektoriális szorzás:

In [ ]:
print(np.outer(v1, v2))

és a skaláris szorzás:

In [ ]:
print(np.inner(v1, v2))

vagy számmal a való szorzás:

In [ ]:
print(v1 * 3)

ha egyszerűen a összeszorozzuk a két vektort akkor a megfelelő hely lévő tagokat szorozaz össze:

In [ ]:
print(v1 * v2)

Transzponálhatjuk is a vektorainkat a `transpose` metódussal bár vektorok esetén itt nem látványos:

In [ ]:
print(v3)
print(v3.transpose())

Komolyabb műveletek mint a vektor normák kiszámítása is egyszerű. Vegyük először az 1-es normát:

In [ ]:
print(np.linalg.norm(v1, 1))

Itt használtuk a numpy `linalg` csomagját melyben előre definiálva vannak a különbőző lineáris algebrához tartozó műveletek, módszerek. Most nézzük a 2-es és a végtelen normát:

In [ ]:
print(np.linalg.norm(v1, 2))
print(np.linalg.norm(v1, np.inf))

Mind itt a vektorműveleteknél és majd a mátrix műveleteknél sem árt figyelni, hogy megfelelő dimenziójú vektorokat, mátrixokat adjunk meg a műveletekhez, különben könnyen hibát vagy helytelen eredményt kaphatunk.

## Mátrixok:

A Mátrixok létrehozása is többféleképpen történhet hasonlóképpen mint a vektoroknál. Legegyszerűbb módszer az ha megadjuk mi, hogy milyen mátrixot szeretnénk vagy képezhetjük vektorokból is, estleg a fent megismert `empty, zeros, ones, random.rand, full` metódusoknak megadjuk a nekünk megfelelő dimenziókat.

In [9]:
m1 = np.matrix([[1, 2, 4], [2, 3, 4]])
m2 = np.matrix([[1, 2, 8], [2, 3, 9]])
m3 = np.matrix([[1, 2], [2, 3], [4, 5]])
m4 = np.matrix([[1, 2], [3, 4]])

print("m1\n", m1)
print("m2\n", m2)
print("m3\n", m3)
print("m4\n", m4)

m1
 [[1 2 4]
 [2 3 4]]
m2
 [[1 2 8]
 [2 3 9]]
m3
 [[1 2]
 [2 3]
 [4 5]]
m4
 [[1 2]
 [3 4]]


In [ ]:
m = np.arange(16.0)
print(m)

m =np.arange(16.0).reshape(4, 4)
print(m)

A `reshape`-nél vigyázni kell, hogy pontosan akkora elemszámú mátrixot adjunk meg mint amekkora a mostani mátrixunké, különben hibát kapunk.

In [ ]:
m=np.reshape(m,(2,2))

In [ ]:
m=np.reshape(m,(16,16))
m

In [ ]:
Ha mégis kissebb vagy nagyobb mátrixot szeretnénk használni át kell másolni az elemeket egyik mátrixból a másikba.

In [ ]:
m = np.empty([3, 3])

print(m)

In [ ]:
m = np.empty([1, 3])
m = np.empty([3])
m = np.empty((3,))
m

In [ ]:
m = np.zeros([3, 3])

print(m)

In [ ]:
m = np.ones([3, 3])

print(m)

In [ ]:
m = np.random.rand(3, 3)

print(m)

In [ ]:
m = np.full([3, 3], 4)

print(m)

Az `eye` metódu segítségével képezhetünk $n*n$-es egységmátrixot, paraméterként a dimenziót kell megadnunk.

In [10]:
m = np.eye(3)
print(m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


A vektorokhoz hasonlóan adhatjuk meg a mátrix műveleteket is, mint az összeadást, kivonást, szorzást, normát:

In [ ]:
print(m1 + m2)

In [ ]:
print(m1 - m2)

In [ ]:
print(m1 * m3)

Forbenius norma:

In [ ]:
print(np.linalg.norm(m1, 'fro'))

Végtelen norma:

In [ ]:
print(np.linalg.norm(m1, np.inf))

1-es norma:

In [ ]:
print(np.linalg.norm(m1, 1))

2-es norma

In [ ]:
print(np.linalg.norm(m1, 2))

A transzponálás is hasonlóan működik:

In [ ]:
print("eredeti:\n", m3)

In [ ]:
print("transzponált:\n", m3.transpose())

Egy négyzetes mátrix determinánsát is egyszerűen és gyorsan kiszámíthatjuk a `linalg.det` metódussal:

In [ ]:
print("m4:\n",m4)

print(np.linalg.det(m4))

In [ ]:
np.linalg.inv(m4)

Egy elemet az `item` metódussal tudunk kiválasztani, de figyelni kell, mert az indexelés 0-tól kezdődik:

In [ ]:
print("m3\n", m3)
print("m3-as mátrix 2.sor 1. eleme", m3.item(1, 0))

A mátrixokat feldarabolhatjuk a `hsplit` és `vsplit` metúdusok segítségével. A `hsplit` oszlopok mentén, míg a `vsplit` sorok mentén vágja el a megadott mátrixot.

In [ ]:
m = np.arange(16.0).reshape(4, 4)
print(m)

print(np.hsplit(m, 2),"\n")
print(np.vsplit(m, 2),"\n")

In [ ]:
print(m)
a, b = np.hsplit(m, 2)
print(a)
print(b)

Használhatjuk vágásra az `[]` operátorokat is, ha csak egy paramétert adunk meg neki akkor az adott indexű sort kapjuk  vissza, ha használjuk a `:` operátort akkor megadhatunk neki intervallumot is, hogy hanyadik sornál kezdje, megadhatunk neki lépésközt is illetve részeket is kivághatunk egy adott mátrixból 

In [ ]:
m[3]

In [ ]:
m[1:3]

In [ ]:
m[:, 1:3]

In [ ]:
m[1:3,1:3]

Ha adunk meg neki lépésközt, akkor az az utolsó paraméter. Pl: az egész mátrix minden párátlan számú sorának és oszlopának  a közös elemei.

In [ ]:
m[0:4:2, 0:4:2]

## Mátrix felbontások

### LU felbontás 

Mátrixok LU felbontásásval kinyerhetjük a felső- ,alsóháromszög mátrixot. Pythonban erre használható a`Scipy.linalg.lu` metódus ami a `SciPy` tudományos csomagban találhatunk meg ami egy kiegészítése tulajdon képpen a `NumPy`-nak. Először telepíteni és importálni kell ezt a csomagot és utána használatba lehet venni. Az `lu` metódus végeredményként visszaadja az alsó-, felső-, és a permutáció mátrixokat. 

In [18]:
import scipy as sp
from scipy.linalg import lu
m =np.arange(16.0).reshape(4, 4)
P, L, U = sp.linalg.lu(m)
print(U)

[[ 1.20000000e+01  1.30000000e+01  1.40000000e+01  1.50000000e+01]
 [ 0.00000000e+00  1.00000000e+00  2.00000000e+00  3.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00 -4.44089210e-16 -9.99200722e-16]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  5.55111512e-16]]


### Cholesky felbontás 

A Cholesky féle felbontásra is találunk beépített metódust a `Numpy`-ban `cholesky` néven a `linalg` csomagban. Cholesky felbontásnál vigyázni kell hogy a mátrixunk szimmetrikus legyen és pozitív definit ellenben hibaüzenetet kapunk. Ugyan ez megtalálható a `SciPy` csomagban is és a különbség az, hogy a `NumPy`-ban lévő metódus az alsó-, addig a `SciPy`-ban lévő a felsőháromszög mátrixot számolja.

In [19]:
#példa olyan esetre mikor a mátrix nem pozitv definit
m =np.arange(16.0).reshape(4, 4)
L=np.linalg.cholesky(m)
print(L)

LinAlgError: Matrix is not positive definite

A fenti kód hibát eredményezett, mert a megadott mátrix nem volt pozitív definit. A következő cellában már pozitív definit mátrixra van példa. 

In [20]:
#példa jó mátrixra
m =np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
L=np.linalg.cholesky(m)
print("\nNumPy:\n")
print(L)
print("\nSciPy:\n")
L=sp.linalg.cholesky(m)
print(L)


NumPy:

[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.22474487  0.        ]
 [ 0.         -0.81649658  1.15470054]]

SciPy:

[[ 1.41421356 -0.70710678  0.        ]
 [ 0.          1.22474487 -0.81649658]
 [ 0.          0.          1.15470054]]


De akár megírhatjuk a saját felbontó függvéníünket is:

In [22]:

import numpy as np
import scipy as sp

#implementation of Cholesky disassembly method

def Cholesky(M,dimensions):
    P, L, U=sp.linalg.lu(M)
    k=0
    
    while (k<dimensions):
        j=0
        sum=0
        while (j<k-1):
            sum=L[k,j]*L[k,j]
            j+=1
        L[k,k]=np.sqrt(M[k,k]-sum)
        i=k+1
        while (i<dimensions):
            j=0
            sum=0
            while (j<k-1):
                sum=L[i,j]*L[k,j]
                j+=1
            L[i,k]=(M[i,k]-sum)/L[k,k]
            i+=1
        k+=1
        
    return L

m =np.array([[2,-1,0],[-1,2,-1],[0,-1,2]])
dimension=3
l=Cholesky(m,dimension)
print(l)


[[ 1.41421356  0.          0.        ]
 [-0.70710678  1.41421356  0.        ]
 [ 0.         -0.70710678  1.41421356]]


Mint ahogy láthajuk a metódus megadja egy közelítő megoldását a cholesky felbontásnak.